---
title: "Tarea Descomposición"
format: html
editor: visual
author: "Ana Sofía Hinojosa Bale"
---

# Tarea

## 1 
 
```{r}
library(tidyverse)
library(fpp3)
```


```{r}
pib_tsbl <- global_economy |> 
  autoplot(GDP/Population) + 
  theme(legend.position = "none")

pib_tsbl
```

Cómo ha sido la evolución de la economía de los países en el tiempo?

Ha incrementado en la mayoría de los países, ya que las series tienen una tendencia alcista, lo que significa que el PIB per cápita ha ido creciendo a lo largo del tiempo.


¿Cuál país tiene el mayor PIB per cápita?

```{r}
global_economy |>
  mutate(gdp_per_capita = GDP/Population) |>
  select(-c(Code, Growth:Exports)) |>
  filter(Year %in% 2010:2017) |>
  as_tibble() |>
  group_by(Country) |>
  summarise(mean_gdppc = mean(gdp_per_capita, na.rm = TRUE)) |>
  arrange(desc(mean_gdppc))

```

## 2

###i

```{r}
pibusa_tsbl <- global_economy |> 
  filter(Country == "United States") |> 
  autoplot(GDP) + ggtitle("PIB de Estados Unidos")
pibusa_tsbl
```
```{r}
pibusa_log <- global_economy |> 
  filter(Country == 'United States') |> 
  autoplot(log(GDP)) + ggtitle("PIB de Estados Unidos con transformación logarítmica")
pibusa_log
```
### ii

```{r}
pibmex_tsbl <- global_economy |> 
  filter(Country == "Mexico") |> 
  autoplot(GDP) + ggtitle("PIB de México")
pibmex_tsbl
```

```{r}
pibmex_log <- global_economy |> 
  filter(Country == "Mexico") |> 
  autoplot(log(GDP)) + ggtitle("PIB de México con transformación logarítmica")
pibmex_log
```
### iii

```{r}
vic_elec |> 
  autoplot(Demand) + ggtitle("Demanda de electricidad en el estado de Victoria (Australia)")
```

```{r}
vic_log <- vic_elec |> 
  autoplot(log(Demand)) + ggtitle("Demanda de electricidad en el estado de Victoria (Australia)")
vic_log
```
¿Qué efectos tuvieron las transformaciones?

## 3

```{r}
canadian_gas |> 
  autoplot()

```

```{r}
# Transformación Box-Cox

(lambda <- canadian_gas %>%
  features(Volume, features = guerrero) %>%
  pull(lambda_guerrero))
  
canadian_gas %>% autoplot(box_cox(Volume, lambda))

```

## 4

```{r}
fma::plastics |> 
  autoplot()
```

### Descomposición Clásica
```{r}
plastics_tsbl
```

```{r}
plastics_tsbl <- as_tsibble(fma::plastics)
```


```{r}
plastics_decomp <- plastics_tsbl |> 
  model(
    clasica = classical_decomposition(value, 
                                      type = "multiplicative")
  )
```


```{r}
plastics_components <- plastics_decomp |> 
  components()

plastics_components
```
```{r}
plastics_components |> 
  autoplot()
```
```{r}
datos_desestacionalizados <- plastics_components |>
  select(index, season_adjust)
autoplot(datos_desestacionalizados)  
```
```{r}
outlier_tsbl <- plastics_tsbl |> 
  mutate(value = value + 500  * (value == 776))

outlier_tsbl
```

```{r}
outlier_decomp <- outlier_tsbl |> 
  model(
    clasica = classical_decomposition(value, 
                                      type = "multiplicative"))

outlier_components <- outlier_decomp |> 
  components() 

outlier_components |> 
  autoplot()
```

```{r}
outlier_desestacionalizados <- outlier_components |>
  select(index, season_adjust)
autoplot(outlier_desestacionalizados)  
```



