---
title: "SARIMA"
author: "Sofía Hinojosa y Julia Hernández"
format: 
  html:
    embed-resources: true
    toc: true
editor: visual
---

# EJERCICIO SARIMA

```{r pkgs, message=FALSE}
library(tidyverse)
library(fpp3)
library(patchwork)
```

## Datos y transformaciones
```{r}
h02 <- PBS |> 
  filter(ATC2 == "H02") |> 
  summarise(Cost = sum(Cost)/1e6)

h02

h02 |> 
  mutate(log(Cost)) |> 
  gather() %>%
  ggplot(aes(x = Month, y = value)) +
  geom_line() +
  facet_grid(key ~ ., scales = "free_y") +
  xlab("Year") + ylab("") +
  ggtitle("Cortecosteroid drug scripts (H02)")
```


```{r, warning = FALSE}
h02 |> 
  gg_tsdisplay(difference(log(Cost), 12), plot_type='partial', lag_max = 48)

h02 |> 
  gg_tsdisplay(log(Cost) |> 
                 difference(12) |> 
                 difference(), plot_type='partial', lag_max = 48)
```
## Datos de entrenamiento

```{r}
h02_train <- h02 |> 
  filter_index(.~ '2006 jun.')

h02_train
```
## Modelos

```{r, warning = FALSE}

fit <- h02_train |> 
  model(
    arima211_213 = ARIMA(log(Cost) ~ pdq(2,1,1) + PDQ(2,1,3) + 1),
    arima212_011 = ARIMA(log(Cost) ~ pdq(2,1,2) + PDQ(0,1,1)),
    arima210_312 = ARIMA(log(Cost) ~ pdq(2,1,0) + PDQ(3,1,2) + 1),
    arima312_123 = ARIMA(log(Cost) ~ pdq(3,1,2) + PDQ(1,2,3) + 1),
    arima112_211 = ARIMA(log(Cost) ~ pdq(1,1,2) + PDQ(2,1,1)),
    arima212_212 = ARIMA(log(Cost) ~ pdq(2,1,2) + PDQ(2,1,2) + 1)
    
  )
fit
glance(fit) |>  
  arrange(AICc)
```

```{r}
accuracy(fit) |> 
  arrange(MAPE)
```


```{r}
fit |> 
  select(arima211_213) |> 
  gg_tsresiduals()

fit |> 
  select(arima210_312) |> 
  gg_tsresiduals()

fit |> 
  select(arima212_212) |> 
  gg_tsresiduals()
```

```{r}
fit |> 
  augment() |> 
  features(.innov, ljung_box, lag = 24)
```
## Comparación de los modelos en test

```{r, warning = FALSE}
h02_fc <- fit |> 
  forecast(h = '2 years')

h02_fcn <- h02_fc |> 
  autoplot(h02 |> 
             filter_index('2005' ~.), level = NULL)

h02_fcn


h02_fcs <- h02_fc |> 
  autoplot(h02 |> 
             filter_index('2005' ~.))

h02_fcs

h02_fct <- h02_fc |> 
  autoplot(h02 |>
             filter_index('2005' ~.))+ 
  facet_wrap(~ .model, ncol = 3)+ 
  theme(legend.position = NULL)

h02_fct
```

```{r}
h02_fc |> 
  accuracy(h02) |> 
  arrange(MAPE)
```

## Pronóstico

```{r, warning = FALSE}
h02_fut <-  h02|> 
  model(
  arima210_312 = ARIMA(log(Cost) ~ pdq(2,1,0) + PDQ(3,1,2) + 1)  
  ) |> 
  forecast(h = '2 years')
```

```{r}
h02_fut |> 
  autoplot(h02, color = 'hotpink4')+
  ggtitle('Pronóstico SARIMA h02')

h02_fut |> 
  autoplot(h02 |> filter_index('2005 jan' ~.), color = 'palevioletred')+
  ggtitle('Pronóstico SARIMA h02')
```